resources:
- frontend/
- backend/
- database/
- ingress/

namespace: default

configMapGenerator:
- literals:
  - ASPNETCORE_ENVIRONMENT=Development
  name: common-config

images:
- name: capstoneasr.azurecr.io/optum-azure-capstone-express-server
  newTag: v2
- name: capstoneasr.azurecr.io/optum-azure-capstone-flask-api
  newTag: v1
- name: keinos/sqlite3
  newTag: latest
- name: capstoneasr.azurecr.io/optum-azure-capstone-angular-app
  newTag: v4
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
